version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/pizza
    ports:
      - 8000:8000
    image: app:pizza
    container_name: my_first_pizza_container
    command: python3 manage.py runserver 0.0.0.0:8000
